# Generated by Django 5.2.5 on 2026-01-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TasksManagementApp", "0001_initial"),
    ]

    operations = []
