# Generated by Django 5.2.5 on 2026-01-04 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("TasksManagementApp", "0002_employee_password"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = []
