# Generated by Django 5.2.5 on 2026-01-04 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "TasksManagementApp",
            "0003_alter_employee_options_alter_employee_managers_and_more",
        ),
    ]

    operations = []
