# Generated by Django 5.2.5 on 2026-01-04 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("TasksManagementApp", "0005_initial"),
    ]

    operations = []
