# Generated by Django 5.2.5 on 2026-01-04 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TasksManagementApp", "0006_auto_20260104_1700"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="team_code",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="TasksManagementApp.team",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="team_manager_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="managed_teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
