# Generated by Django 5.2.5 on 2026-01-04 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "TasksManagementApp",
            "0007_alter_employee_team_code_alter_team_team_manager_id",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="team_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="TasksManagementApp.team",
            ),
        ),
    ]
