# Generated by Django 5.2.5 on 2026-01-04 16:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("TasksManagementApp", "0008_alter_employee_team_code"),
    ]

    operations = []
