# Generated by Django 5.2.5 on 2026-01-04 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TasksManagementApp", "0009_auto_20260104_1851"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="team_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="TasksManagementApp.team",
            ),
        ),
    ]
