# Generated by Django 5.2.6 on 2026-01-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TasksManagementApp", "0010_alter_employee_team_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_completed_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
