# Generated by Django 5.2.6 on 2026-01-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TasksManagementApp", "0013_alter_task_task_last_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_last_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
